[package]
name = "minigrep"
version = "0.1.0"
edition = "2018"
authors = ["Subhojit Paul <subhojitpaul21@gmail.com>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "1.6.0"